#!/bin/bash -x
#SBATCH --account=mul-tra
#SBATCH --job-name=E250-TRAD-28-8
#SBATCH --nodes=56
#SBATCH --ntasks-per-node=27
#SBATCH --cpus-per-task=1
#SBATCH --output=result
#SBATCH --error=err_file
#SBATCH --time=01:00:00
#SBATCH --partition=batch



export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
#module load 2022a
module load GCC/11.3.0
module load OpenMPI/4.1.4


date
make clean
make -j 64


date
. run -i "192x96to3.ini"

date


