#!/bin/bash
#SBATCH --job-name=64x32to3_trace
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --output=result
#SBATCH --error=err_file
#SBATCH --time=96:00:00
#SBATCH --mail-type=ALL           # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=mariopapacee@gmail.com  # Your email address

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
#module load 2022a
module load GCC/11.3.0
module load OpenMPI/4.1.4

make clean
make -f Makefile -j 32

. run -i "64x32to3.ini"
date
